# Generated by Django 2.2.24 on 2021-09-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('dgyryrturut', models.BigIntegerField(blank=True, null=True)),
                ('drgyeryeyrthyfh', models.BigIntegerField(blank=True, null=True)),
                ('ghjfhfhdgdgdg', models.BigIntegerField(blank=True, null=True)),
                ('fgdfg', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jngjhgj', models.BigIntegerField()),
                ('cgvfbgbhnjnmj', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
